# Site settings
title: "Cody Ernesti - Systems Engineer"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Cody Ernesti"
resume_title:                   "Systems Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "cody@ernesti.tech"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "785-317-3907"
resume_contact_address:         "Elkhorn, NE"

resume_header_contact_info:     'Elkhorn, NE • (785) 317-3907 • <a href="mailto:cody@ernesti.tech">cody@ernesti.tech</a>'
display_header_contact_info:    "true"

resume_header_intro: "<p>Proven systems engineer with diverse skillset focusing in automation and security. Managed over a hundred servers (physical and virtual), in addition to network equipment over multiple locations. Seeking position in a fast-paced company utilizing cutting-edge technologies to solve unique problemsets.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_certification:   true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_software:        true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Soarinferret"
  # resume_twitter_url:           "https://twitter.com/thecodye"
  # resume_dribbble_url:          "insert Dribble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://linkedin.com/in/cernesti"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://blog.kanto.cloud"
  #resume_medium_url:            "insert Medium URL here"
resume_print_social_links:      true

# Resume Print Button
# uncomment to remove button
resume_print_button:            "yes"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts